### ISSUE TITLE
In need of clever way to use different yardoc (not yard server!) options under Guard

### ISSUE THREAD

**Issue by L2G** [panthomakos/guard-yard#10]
I'm trying to figure out a good way to get the `--private` and `--protected` options passed to yardoc when Guard runs the Yard server, while leaving .yardopts alone for generating normal documentation.

Can this be done with guard and guard-yard as they stand today, or would this require a code change?

**Comment by panthomakos** [comment]
Assuming the `cli` option solves this problem. Please re-open the issue if that is not the case.
